### ISSUE TITLE
Skyfield load issue

### ISSUE THREAD

**Issue by jblake95** [jblake95/pyTLE#2]
Every so often, Skyfield's load.timescale() will return an error of the form:
"""Traceback (most recent call last):
  File "catForRun.py", line 13, in <module>
    TS = load.timescale()
  File "/home/james/.local/lib/python3.5/site-packages/skyfield/iokit.py", line 270, in timescale
    preds = self('deltat.preds')
  File "/home/james/.local/lib/python3.5/site-packages/skyfield/iokit.py", line 184, in __call__
    expiration_date, data = parser(f)
  File "/home/james/.local/lib/python3.5/site-packages/skyfield/iokit.py", line 347, in parse_deltat_preds
    expiration_date = date(year[0] + 2, month[0], 1)
ValueError: year is out of range"""

**Comment by jblake95** [comment]
This is due to bugs in the timescale files on the server. Solution is to either wait for the files to update or use older versions that do not raise the error - i.e. copy the deltat.data and deltat.preds files to the directory containing the Python script in question.
